<a href="https://colab.research.google.com/github/annazhao1111/LinearAlgebra/blob/master/linalg_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [4]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
Z2 = np.zeros((3,3), dtype=complex)
print(Z), print(' ')
print(Z2), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')
print(U), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 0.42641667  2.11530364 -0.95222922  0.53546121 -0.70077994]
 [ 0.11799246  0.34990376  0.55586826  1.32491956 -0.1338398 ]
 [ 0.17814464  2.14162075  0.2394032   1.15764432  0.45751535]
 [-0.11018612 -0.84231806 -0.6088762   1.3498159   1.7963812 ]
 [ 2.59523557 -0.73047081 -1.36329998 -0.23916458  1.06362841]]
 
[[-0.58001664 -0.3201533 ]
 [ 2.19566674 -0.19118174]
 [ 1.77113152 -0.02726152]
 [-2.09282983  0.62533816]
 [ 0.37837264 -0.06301175]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 1.14784156  0.          0.          0.          0.        ]
 [-1.22643985 -0.07029184  0.          0.          0.        ]
 [-0.76118186 -0.17879301 -0.34962864  0.          0.        ]
 [-1.45814105  0.21379844 -0.26088611 -0.93602762  0.        ]
 [ 0.00748122 -0.08848524  0.7262454   0.72100152


---
# VIDEO: Matrix addition and subtraction
---


In [5]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B
A+C



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[-0.81694092 -0.08377905 -1.9821972   0.32393868 -1.19994252]
 [ 1.46913977  0.06538328 -0.02759352 -0.79547641 -0.1832567 ]
 [ 1.13097963 -0.52132003  0.51185305 -1.89404003  0.44958639]
 [ 1.49269466 -0.02899099 -0.14774622 -0.84655099 -1.21963968]
 [ 0.58260571 -0.02757115  1.76220117  1.08792341  0.03652068]]
 
[[-0.78694092 -0.08377905 -1.9821972   0.32393868 -1.19994252]
 [ 1.46913977  0.09538328 -0.02759352 -0.79547641 -0.1832567 ]
 [ 1.13097963 -0.52132003  0.54185305 -1.89404003  0.44958639]
 [ 1.49269466 -0.02899099 -0.14774622 -0.81655099 -1.21963968]
 [ 0.58260571 -0.02757115  1.76220117  1.08792341  0.06652068]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [6]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# VIDEO: Transpose

In [7]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [8]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [9]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[ -4.   5.   1.   0.]
 [  7.  -8.   6.  -6.]
 [ -2.   5. -10.  -3.]
 [ -4.   4.  -2.   5.]]
 
[ -4.  -8. -10.   5.]
[[ -4.   0.   0.   0.]
 [  0.  -8.   0.   0.]
 [  0.   0. -10.   0.]
 [  0.   0.   0.   5.]]
-17.0 -17.0


In [10]:
# whether the trace is linear

# tr(A) + tr(B) == tr(A+B)?
# tr(l*A) == l*tr(A)?

m = 4
n = 4

A = np.random.randn(m, n)
B = np.random.randn(m, n)
l = np.random.rand()

print('tr(A+B) = ' + str(np.trace(A+B)))
print('tr(A)+tr(B) = ' + str(np.trace(A)+np.trace(B)))
print('**************')

print('tr(l*A) = ' + str(np.trace(l*A)))
print('l*tr(A) = ' + str(l*np.trace(A)))

tr(A+B) = -0.7884482037649816
tr(A)+tr(B) = -0.7884482037649817
**************
tr(l*A) = 0.08951598352222884
l*tr(A) = 0.08951598352222885



---
# VIDEO: Broadcasting matrix arithmetic
---


In [11]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') #F=column, C=row

# and two vectors
r = [10,20,30,40]
c = [100,200,300]
print(A), print('*********')
print(r), print('*********')
print(c), print('*********')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
*********
[10, 20, 30, 40]
*********
[100, 200, 300]
*********


(None, None)

In [12]:
# broadcast on the rows
print(A+r), print('***********')

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
***********


(None, None)

In [16]:
# broadcast on the colunms
# print(A+c) # not work
c_r = np.reshape(c, (len(c),1))
print(c_r)
print('*************')
print(A+c_r)

[[100]
 [200]
 [300]]
*************
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
