<a href="https://colab.research.google.com/github/annazhao1111/LinearAlgebra/blob/master/linalg_matrixRank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [2]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# set last column to be repeat of penultimate column
B = A
B[-1,:] = B[-2,:]

rb = np.linalg.matrix_rank(B)
print('rank = ' + str(rb))

rank = 4
rank = 3


In [3]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4



---
# VIDEO: Rank of A^TA and AA^T
---


In [4]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [5]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30


In [10]:
# determine whether this vector 
v = np.array([[1,2,3,4]]).T
# print(v)

# in the span of these sets?
S = np.vstack(([4,3,6,2],[0,4,0,1])).T
T = np.vstack(([1,2,2,2],[0,0,1,2])).T
print(S)
print(T)

Sv = np.concatenate((S,v), axis=1)
Tv = np.concatenate((T,v), axis=1)
print(Sv)
print(Tv)
print('*************')
print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
*************
3
2
